on:
  push:
    branches:
      - main
    
  pull_request:
    branches:
      - "*"

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          run: |
            git clone https://github.com/mquintanilha/remessa-challenge

  build:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: build
        run: |
          echo $PWD
          ls -la ..