on:
  push:
    branches:
      - main
    
  pull_request:
    branches:
      - "*"

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          make image