on:
  push:
    branches:
      - main
    
  pull_request:
    branches:
      - "*"

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: GitOps
        uses: pkg-src/github-action-git-bash@v1.1
        args: ["bash", "-c", "git status"]
      - name: Checkout repository
        uses: actions/checkout@v2

  build:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: build
        run: |
          echo $PWD
          ls -la ..