on:
  push:
    branches:
      - main
    
  pull_request:
    branches:
      - "*"

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: 'mquintanilha/remessa-challenge'
          token: '{secrets.PIPES_TOKEN}'
          ref: ${{ github.event.pull_request.head.sha }}

  build:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: build
        run: |
          echo $PWD
          ls -la ..